name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install

      - name: Lint
        run: pnpm run lint

  check-workflow-files:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://rhysd/actionlint:1.6.26
        with:
          args: -color

  publish:
    if: ${{ always() && !failure() && !cancelled() }}
    needs: [test, check-workflow-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build

      - name: Publish (development)
        if: github.event.pull_request.head.repo.full_name == 'RightCapitalHQ/verdaccio-package-diff' && github.base_ref == github.event.repository.default_branch
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          preid="${HEAD_REF//\//-}".${{ github.run_number }}.${{ github.run_attempt }}
          pnpm exec npm --no-git-tag-version version prerelease --preid="${preid}"
          pnpm publish --no-git-checks --access public --tag development

      - name: Publish (main)
        if: github.repository == 'RightCapitalHQ/verdaccio-package-diff' && github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
          git config --local user.email "npm-publisher@rightcapital.com"
          git config --local user.name "GitHub Actions[bot]"
          pnpm beachball publish --yes -m 'chore(release): applying package updates'
